---
- hosts: localhost
  gather_facts: false
  vars:
    - target_host_name: vpn
    - region_id: ams2
    - size_id: 512mb
    - image_id: ubuntu-16-04-x64
  tasks:
  - include: tasks/install_python_packages.yml
  - digital_ocean: >
      state=present
      api_token={{ do_api_token }}
      command=droplet
      name={{ target_host_name }}
      size_id={{ size_id }}
      region_id={{ region_id }}
      image_id={{ image_id }}
      ssh_key_ids={{ do_ssh_key_id }}
      wait_timeout=500
    register: my_droplet
  - lineinfile: >
      dest=/etc/hosts
      regexp="{{ target_host_name }}$"
      state=present
      line="{{ my_droplet.droplet.ip_address }} {{ target_host_name }}"
    become: yes
  - lineinfile: >
      dest=/etc/ansible/hosts
      regexp="^vpn.*root"
      insertbefore=BOF
      state=present
      line="{{ target_host_name }} ansible_ssh_user=root"
    become: yes
  - shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ target_host_name }}'
