---
- name: install openvpn server
  apt: pkg=openvpn state=installed

- name: create masquerading script
  copy:
    src=files/do_masquerade.sh
    dest=/usr/local/sbin/do_masquerade
    owner=root
    group=root
    mode=0755

- name: Copy and populate templates
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode={{ item.mode }} backup=yes
  with_items:
      - { src: 'openvpn.conf.j2', dest: '/etc/openvpn/openvpn.conf', mode: '0640' }
      - { src: 'etc_iptables_rules.v4.j2', dest: '/etc/iptables/rules.v4', mode: '0640' }
  notify:
    - restart openvpn
    - reload iptables rules

- name: generate key
  command: '/usr/sbin/openvpn --genkey --secret {{ openvpn_cd }}/{{ keyfile }}'
  notify:
    - restart openvpn

- name: extract key
  command: 'cat {{ openvpn_cd }}/{{ keyfile }}'
  changed_when: no
  register: openvpn_server_secret_result

- name: enable ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1

- name: start openvpn server
  service: name=openvpn enabled=yes state=started
