---
- name: install openvpn server
  apt: pkg=openvpn state=installed

- name: create masquerading script
  copy:
    src=files/do_masquerade.sh
    dest=/usr/local/sbin/do_masquerade
    owner=root
    group=root
    mode=0755

- name: create openvpn config
  template:
    src=templates/openvpn.conf.j2
    dest=/etc/openvpn/openvpn.conf
    backup=yes
  notify:
    - restart openvpn

- name: generate key
  command: '/usr/sbin/openvpn --genkey --secret {{ openvpn_cd }}/{{ keyfile }}'
  notify:
    - restart openvpn

- name: extract key
  command: 'cat {{ openvpn_cd }}/{{ keyfile }}'
  changed_when: no
  register: openvpn_server_secret_result

- name: enable ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1

- name: start openvpn server
  service: name=openvpn enabled=yes state=started
